public class RulesEngineConstants {
	public static final String LOGICAL_OPERATORS = 'AND,OR,and,or,';
	public static final String Yes_No_Values = 'yes,no,true,false,YES,NO,True,False,TRUE,FALSE,Yes,No,1,0';
	public static final String COMBINATION_OPERATORS = '{,},(,)';
	public static final String SOURCE_RULE = 'rule';
	public static final String SOURCE_RULE_COMBINATION = 'combination';
	public static final String SOURCE_OPTUM360_API = 'optum360';
	public static final Set<String> setSOAPNotesRelatedObjects = new Set<String>{'Skin_Abnormality__c', 'SOAP_Note__c'};
}