public class SearchConstants {
	public static final String SEARCH_PARAMS = 'data=desc,rank&maxresults=25';
    public static final String ICD10_SEARCH_PARAMS = '/properties?data=desc-full';
    public static final String ICD9_SEARCH_PARAMS='/icd10mapping';
    public static final String ICD9_Code_FETCH_PARAMS='/icd9mapping?data=desc,rank&maxresults=25';
    public static final String ICD_INSTRUCTIONAL_NOTES_PARAMS='instructional-notes';
    public static final String ICD10_INSTRUCTIONAL_NOTES_ROOTNODE = 'icd10-cm-instructional-notes';
    public static final String ICD_INCLUDE_EXCLUDE_PARAMS='/includesexcludesnotes';
    public static final String ICD10_RANGE_PARAMS = '/range?data=desc-full';
    
    public static final String CODE_PROPERTIES = 'code-properties';
    public static final String DESC_FULL = 'desc-full';
    public static final String HREF_BEG = 'href-beg';
    public static final String NODE = 'node';
    public static final String CODE = 'code';
    public static final String DESCRIBE = 'desc';
    public static final String RANK = 'rank';
    
    public static final String ICD_9_MAPPING = 'icd-9-mapping';
    public static final String NOTIFICATION = 'notifications';
    public static final String ERROR = 'error';
    public static final String HEADER = 'header';
    public static final String NOTE = 'note';
    public static final String CONTENT = 'content';
    public static final String INDENTATION = 'indentation';
    public static final String INCLUDE_EXCLUDE_NOTES = 'includes-excludes-notes';
    public static final String CODE_RANGE = 'code-range';
    public static final String RANGE_ITEM = 'range-item';
    public static final String HREF = 'href';
    public static final String DESCRIPTION = 'description';
    
    public static final String PREFIX = 'prefix';
    public static final String CONTAINS = 'contains';
    public static final String EQUALS = 'equals';
    
}